### PR TITLE
Minor quality-of-life improvements for Taffer v4.1.

### PR DESCRIPTION
**Pull request by nc-z**
Apologies for another one so soon! Just trying to keep all of my work in sync. Just a few minor improvements. If you want me to collect changes over a longer period of time and only keep my work here in sync every few versions, let me know.

### CODE REVIEW

**Comment by PeridexisErrant** [comment]
Hmm.  I'm certainly keen on keeping up-to-date, but past a certain point it would be good to use the actual updater functionality of the scripts rather than changing the base files.

Do you maintain an up-to-date copy on Github (with tagged releases) or DFFD?

**Comment by PeridexisErrant** [comment]
Hmm. I'm certainly keen on keeping up-to-date, but past a certain point it would be good to use the actual updater functionality of the scripts rather than changing the base files.  (and five releases in ten hours is well past that!)

I'll add your repo to `components.yml` instead.

**Comment by PeridexisErrant** [comment]
4d42407463fd762b8de0132635ccd36cd3f05be1 implements this change.

Now I just have to fix a ~~small~~ bug (GH tags arrive sorted by name, not date!) and it'll work without any further integration work for either of us,

**Comment by nc-z** [comment]
I do apologize about the 5 releases in 10 hours. Only two of those releases were of much consequence, to be fair: neither affected my work here. I don't update DFGraphics either for the minor point releases. Didn't intend to make things annoying.

I'll work on better quality control for future releases: things always seem to slip by, even when I've double checked them. 

It should automatically update from DFGraphics then?

**Comment by PeridexisErrant** [comment]
> It should automatically update from DFGraphics then?

It will use the source code zip from the latest thing at https://github.com/nc-z/taffer/releases

**Pull request merged**
